# Generated by Django 6.0.5 on 2026-05-29 18:14

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('receipt_date', models.DateTimeField()),
                ('currency', models.CharField(max_length=10)),
                ('subtotal', models.FloatField(default=0)),
                ('tax_amount', models.FloatField(default=0)),
                ('total_amount', models.FloatField(default=0)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='ledger.category')),
                ('payment_card', models.ForeignKey(blank=True, db_column='payment_card_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='ledger.paymentcard')),
                ('shop', models.ForeignKey(blank=True, db_column='shop_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='ledger.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'receipts',
                'ordering': ['-receipt_date'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.FloatField(default=1)),
                ('unit_price', models.FloatField(default=0)),
                ('line_total', models.FloatField(default=0)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='ledger.receipt')),
            ],
            options={
                'db_table': 'receipt_line_items',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['user', 'receipt_date'], name='ix_receipts_user_date'),
        ),
    ]
