# Generated by Django 6.0.5 on 2026-05-29 18:19

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_receipt_receiptlineitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmortizationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('total_amount', models.FloatField(default=0)),
                ('months', models.IntegerField(default=12)),
                ('monthly_amount', models.FloatField(default=0)),
                ('status', models.CharField(default='active', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amortization_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'amortization_rules',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PairingToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=512, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairing_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pairing_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringExpenseTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('expected_amount', models.FloatField(default=0)),
                ('frequency', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_expense_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recurring_expense_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecurringExpenseOccurrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('due_date', models.DateTimeField()),
                ('status', models.CharField(default='upcoming', max_length=50)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='ledger.recurringexpensetemplate')),
            ],
            options={
                'db_table': 'recurring_expense_occurrences',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='SyncEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=255)),
                ('sync_started_at', models.DateTimeField()),
                ('sync_completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='success', max_length=50)),
                ('receipts_count', models.IntegerField(default=0)),
                ('line_items_count', models.IntegerField(default=0)),
                ('categories_count', models.IntegerField(default=0)),
                ('shops_count', models.IntegerField(default=0)),
                ('cards_count', models.IntegerField(default=0)),
                ('duplicates_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sync_events',
                'ordering': ['-sync_started_at'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year_month', models.CharField(max_length=7)),
                ('mode', models.CharField(max_length=50)),
                ('amount', models.FloatField(default=0)),
                ('adjustment_pct', models.IntegerField(blank=True, null=True)),
                ('rollover_enabled', models.BooleanField(default=False)),
                ('rollover_balance', models.FloatField(default=0)),
                ('category', models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='ledger.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'budgets',
                'ordering': ['-year_month'],
                'constraints': [models.UniqueConstraint(fields=('user', 'year_month', 'category'), name='uq_budget_scope')],
            },
        ),
    ]
